from flask import Flask, request
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time, os, requests

app = Flask(__name__)
BOT_TOKEN = os.getenv("BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("CHAT_ID")
LOGGER_GROUP_ID = os.getenv("LOGGER_GROUP_ID", TELEGRAM_CHAT_ID)  # Optional logger group

WELCOME_MSG_TEMPLATE = (
    "❤️‍🔥 *ᴡᴇʟᴄᴏᴍᴇ ᴛᴏ ʜᴇᴀʀᴛᴀʙʟᴇ ᴀɪ, {name}* ❤️‍🔥\n\n"
    "╭━━━┳━━━┳━━━╮\n"
    "┃💬 sᴍᴀʀᴛ ᴄʜᴀᴛ\n"
    "┃🎥 ᴠɪᴅᴇᴏ ɢᴇɴᴇʀᴀᴛᴏʀ\n"
    "┃📖 ɪᴅᴇᴀs ᴀᴅᴅᴀ\n"
    "┃🖼 ᴀɪ ɪᴍᴀɢᴇ ɢᴇɴᴇʀᴀᴛᴏʀ\n"
    "╰━━━━┻━━━━┻━━━━╯\n\n"
    "✨ ᴅɪᴠᴇ ɪɴᴛᴏ ᴀ ᴡᴏʀʟᴅ ᴡʜᴇʀᴇ ʜᴇᴀʀᴛs sᴘᴇᴀᴋ.\n"
    "💌 ʟᴇᴛ ʏᴏᴜʀ ᴇᴍᴏᴛɪᴏɴs ғʟᴏᴡ ᴡɪᴛʜ ʜᴇᴀʀᴛᴀʙʟᴇ ᴀɪ.\n\n"
    "📌 *Available Commands:*\n"
    "• `/chat` – Smart Chat\n"
    "• `/video` – AI Video Generator\n"
    "• `/image` – AI Image Generator\n\n"
    "━━━━━━━━━━━━━━━━━━\n"
    "👑 *ᴏᴡɴᴇʀ:* [sᴀɴᴋɪ](tg://user?id=7549407961)\n"
    "*ᴠɪsɪᴛ ɴᴏᴡ:* [ʜᴇᴀʀᴛᴀʙʟᴇ ᴀɪ](https://www.heartable.site)\n"
    "━━━━━━━━━━━━━━━━━━"
)

@app.route("/start", methods=["POST"])
def start():
    data = request.json or {}
    user = data.get("from", {})
    name = user.get("first_name", "User")
    username = user.get("username", "unknown")
    user_id = user.get("id", "0")

    welcome_caption = WELCOME_MSG_TEMPLATE.format(name=name)

    photo_url = "https://graph.org/file/3afe8fb057b85cfb7ab81-d7fad6cbb095587f2e.jpg"  # Example welcome image
    payload = {
        "chat_id": user_id,
        "photo": photo_url,
        "caption": welcome_caption,
        "parse_mode": "Markdown"
    }
    requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendPhoto", data=payload)

    # Log to group
    logger_text = f"👤 New User Started Bot:\n🆔 ID: `{user_id}`\n👤 Name: {name}\n🔗 Username: @{username}"
    requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage", data={
        "chat_id": LOGGER_GROUP_ID,
        "text": logger_text,
        "parse_mode": "Markdown"
    })

    return {"status": "sent"}, 200

@app.route("/generate", methods=["POST"])
def gen():
    data = request.json or {}
    prompt = data.get("prompt", "").strip()
    user = data.get("from", {})
    name = user.get("first_name", "User")
    username = user.get("username", "unknown")
    user_id = user.get("id", TELEGRAM_CHAT_ID)

    if not prompt or not BOT_TOKEN:
        return {"error": "prompt/BOT_TOKEN missing"}, 400

    start = time.time()
    opts = Options()
    opts.add_argument("--headless")
    opts.add_argument("--disable-gpu")
    opts.add_argument("--no-sandbox")
    driver = webdriver.Chrome(ChromeDriverManager().install(), options=opts)

    try:
        url = f"https://www.pollitions.ai/?prompt={prompt.replace(' ','%20')}"
        driver.get(url)
        time.sleep(12)
        path = "/tmp/out.png"
        driver.save_screenshot(path)
        elapsed = round(time.time() - start, 2)
        caption = f"🖼 Image ready in {elapsed}s\nPrompt: {prompt}"

        with open(path, "rb") as f:
            resp = requests.post(
                f"https://api.telegram.org/bot{BOT_TOKEN}/sendPhoto",
                data={"chat_id": user_id, "caption": caption},
                files={"photo": f}
            )

        # Log to group
        log_msg = (
            "📤 *Image Generated by User:*
"
            f"🧑‍💻 *Name:* {name}
"
            f"🔗 *Username:* @{username}
"
            f"🆔 *ID:* `{user_id}`
"
            f"🖼 *Prompt:* `{prompt}`"
        )
        requests.post(f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage", data={
            "chat_id": LOGGER_GROUP_ID,
            "text": log_msg,
            "parse_mode": "Markdown"
        })

        return {"telegram": resp.json()}, 200
    finally:
        driver.quit()

@app.route("/health")
def health():
    return "OK", 200

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
